### ISSUE TITLE
TemplateStart and ReadStart

### ISSUE THREAD

**Issue by guleiathms** [PacificBiosciences/pbh5tools#10]
If I want to extract reads mapped on a certain genomic region, which one should I use?
cmph5tools.py -v select --where "ReadStart>46390719" --outFile chr16_part1.cmp.h5 chr16_sorted.cmp.h5
cmph5tools.py -v select --where "TemplateStart>46390719" --outFile chr16_part1.cmp.h5 chr16_sorted.cmp.h5
Thanks.

**Comment by dalexander** [comment]
the latter
