### ISSUE TITLE
Please tag a stable release

### ISSUE THREAD

**Issue by sjackman** [PacificBiosciences/pbh5tools#11]
Thank you!

**Comment by dalexander** [comment]
@sjackman pbh5tools is effectively deprecated at this point as we are migrating to BAM format for everything

**Comment by sjackman** [comment]
Ah, interesting. To enable old pipelines that use `pbh5tools`, could you please tag a version, such as `0.1` something? It's a lot easier to say that "I used pbh5tools 0.1" rather than "I used pbh5tools 2679c17687a868690595ae0d9e856c2fead28ff9".

**Comment by dalexander** [comment]
try tag smrtanalysis-2.3.0p4

**Comment by sjackman** [comment]
Great. Thanks!
