### ISSUE TITLE
Problem with cmph5tools

### ISSUE THREAD

**Issue by ebioman** [PacificBiosciences/pbh5tools#21]
Hello 
I have a problem merging newly generated *.cmp.h5 files which were generated by pbalign --forQuiver.
If I use the following syntax

    cmph5tools.py merge --outFile merged.cmp.h5 input1.cmp.h5 input2.cmp.h5

I obtain the following error

     cmph5merge() takes exactly 2 arguments (3 given)

I tried other functions such as validate, stats and sort which work flawless.
Any idea where this might stem from ?

**Comment by mhsieh** [comment]
Please try `cmph5tools.py merge --outFile=merged.cmp.h5 input1.cmp.h5 input2.cmp.h5` and see what happens.

**Comment by ebioman** [comment]
Thanks a lot for the swift response. Unfortunately, the outcome is similar:


  cmph5tools.py merge --outFile=merged.cmp.h5 out_1.cmp.h5 out_2.cmp.h5 
<pre><code>
Traceback (most recent call last):
  File "/software/UHTS/PacBio/pbh5tools/0.8.0/bin/cmph5tools.py", line 240, in <module>
    sys.exit(CmpH5ToolsRunner().start())
  File "/home/eschmid/.local/lib/python2.7/site-packages/pbcore-0.8.5-py2.7.egg/pbcore/util/ToolRunner.py", line 105, in start
    return self.run()
  File "/software/UHTS/PacBio/pbh5tools/0.8.0/bin/cmph5tools.py", line 182, in run
    cmpH5Merge(self.args.inCmps, self.args.outCmp, self.args.referencesFile)
TypeError: cmpH5Merge() takes exactly 2 arguments (3 given)
</code></pre>

I am using version 0.8.0 for which I build a module on a CentOS 6 cluster. I tried with a functional terminal version of smrtpipe and received a similar error.

**Comment by mhsieh** [comment]
Works for me: ```sh
$ /opt/smrtportal-2.3.0p5/smrtcmds/bin/smrtwrap cmph5tools.py merge --outFile=merged.cmp.h5 /scratch/1.cmp.h5 /scratch/2.cmp.h5
$ /opt/smrtportal-2.3.0p5/smrtcmds/bin/smrtwrap cmph5tools.py merge --outFile merged.cmp.h5 /scratch/1.cmp.h5 /scratch/2.cmp.h5
```Both work.
I am very curious about how you installed the pbh5tools, since I don't recall "$HOME/.local" being part of the installation at all.

**Comment by mhsieh** [comment]
The pbcore in your ~/.local looks ancient comparing to pbh5tools.py version by the way.

**Comment by ebioman** [comment]
Thanks, that might be part of the problem. I will investigate and check this out-------- Originalnachricht --------Betreff: Re: [pbh5tools] Problem with cmph5tools (#21)Von: Mengjuei Hsieh An: PacificBiosciences/pbh5tools Cc: ebioman The pbcore in your ~/.local looks ancient comparing to pbh5tools.py version by the way.

**Comment by ebioman** [comment]
Hi
I figure out the problem, the path to the python libraries was not correct (used sitelib instead of sitearch). It then looked in my ~/.local next where I had some old junk libraries for testing floating around. 
Therefore it used these very outdated libraries there instead.
