### ISSUE TITLE
how to convert the three *.bax.h5 files to fastq format?

### ISSUE THREAD

**Issue by DanwangJessica** [PacificBiosciences/pbh5tools#24]
how to convert the three *.bax.h5 files to fastq format?

**Comment by ylipacbio** [comment]
You may use pls2fasta to convert *.bax/bas.h5 to fastq. 

pls2fasta was included in S2.3 and all previous release of smrtanalysis. Or you may download blasr ](https://github.com/PacificBiosciences/blasr) and build pls2fasta which is under  blasr/utils.

```
pls2fasta input.bax.h5 output.fastq -fastq
```
