### ISSUE TITLE
File size increased 3 fold after sorting

### ISSUE THREAD

**Issue by wl13** [PacificBiosciences/pbh5tools#31]
I have an 100GB cmp.h5 file, after sorting with "cmph5tools.py sort --deep", I get a new file of 400GB. I know sorting will add additional information, but is this normal for such a big change in file size?

**Comment by pb-jchin** [comment]
try this https://support.hdfgroup.org/HDF5/docNewFeatures/FileSpace/h5repack.htm, maybe it will work

**Comment by wl13** [comment]
"h5repack -f GZIP=1" successfully reduced the file size to ~100GB.  Thanks!
